### PR TITLE
new request

### PR DESCRIPTION
**Pull request by oldeight888**
good job

### CODE REVIEW

**Comment by Maxwell-Tian** [comment]
great

**Review by Maxwell-Tian — APPROVED** [review]

**Review by Icarus02423 — COMMENTED** [review]
Nice work. Now we can use your code to search recipes and convert it into our repository.

**Review by Icarus02423 — COMMENTED** [review]
Good job. The project is originally can't show the ingredient correctly. Now when we are testing the function, the ingredient can show successfully.

**Review by Icarus02423 — APPROVED** [review]
Great. These contents improve the readability and usefulness of our whole project.

**Review by Icarus02423 — APPROVED** [review]
Well done! This little error make our all team members can't run the project. Next time, we should write correct import class to avoid such terrible problems.

**Review by Icarus02423 — APPROVED** [review]
Nice debug. Our project can't run successfully when we change some contents where we don't know. This commit fix the problem successfully. Next time, everyone should be careful before merging your branchs to the main, because you may never know what's the problem is and don't know how to fix it.

**Pull request closed without merging**
