### PR TITLE
Api connect

### PR DESCRIPTION
**Pull request by LucyK222**
API connected and cleaned up

### CODE REVIEW

**Comment by oldeight888** [comment]
Good job, our program is finally up! Ty!

**Comment by LucyK222** [comment]
Lets gooooooooo

**Comment by Icarus02423** [comment]
Great Job!!! Our app now is completely able to work. These content connects our all views successfully. Moreover, our project still follows the clean architecture law.

**Comment by oldeight888** [comment]
Nice job getting the API working! It’s awesome that everything is connected now. But we still gotta figure out how to generate recipes from the ingredients we have. Maybe we can start by listing all the available ingredients and brainstorming a logic to match them with recipe ideas.

**Review by oldeight888 — COMMENTED** [review]
Overall it looks perfect, but I think you should be adding some Jdoc, since the API part is very confusing, Thank you!

**Pull request merged**
